from response_builder.v1.builders.ballots import BallotBuilder, StockLocalBallotBuilder  # noqa

LOCAL_BALLOT = StockLocalBallotBuilder()
PARL_BALLOT = BallotBuilder()
NIA_BALLOT = BallotBuilder()  
EUROPARL_BALLOT = BallotBuilder() 
NAW_BALLOT = BallotBuilder() 
NAW_C_BALLOT = BallotBuilder() 
NAW_R_BALLOT = BallotBuilder() 
SENEDD_BALLOT = BallotBuilder()
SENEDD_C_BALLOT = BallotBuilder()
SENEDD_R_BALLOT = BallotBuilder() 
SP_C_BALLOT = BallotBuilder()
SP_R_BALLOT = BallotBuilder() 
SP_BALLOT = BallotBuilder()  
GLA_BALLOT = BallotBuilder() 
GLA_C_BALLOT = BallotBuilder()
GLA_A_BALLOT = BallotBuilder()
PR_CL_BALLOT = BallotBuilder()
STV_BALLOT = BallotBuilder()
SV_BALLOT = BallotBuilder()
FPTP_BALLOT = BallotBuilder() 
PCC_BALLOT = BallotBuilder()  
MAYOR_BALLOT = BallotBuilder()  
CANCELLED_BALLOT = BallotBuilder()
REF_BALLOT = BallotBuilder()
AMS_BALLOT = BallotBuilder()

